"""
    notifier

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.3.0
    Contact: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.channel_response import ChannelResponse


class TestChannelResponse(unittest.TestCase):
    """ChannelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelResponse(self):
        """Test ChannelResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChannelResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
