"""
    notifier

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.channel_response import ChannelResponse
globals()['ChannelResponse'] = ChannelResponse
from openapi_client.model.channels_response import ChannelsResponse


class TestChannelsResponse(unittest.TestCase):
    """ChannelsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelsResponse(self):
        """Test ChannelsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChannelsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
