"""
    notifier

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.notify_body import NotifyBody


class TestNotifyBody(unittest.TestCase):
    """NotifyBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotifyBody(self):
        """Test NotifyBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotifyBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
