"""
    notifier

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Contact: 
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.crate_api import CrateApi  # noqa: E501


class TestCrateApi(unittest.TestCase):
    """CrateApi unit test stubs"""

    def setUp(self):
        self.api = CrateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_handle_add_email_channel(self):
        """Test case for handle_add_email_channel

        Add email channel  # noqa: E501
        """
        pass

    def test_handle_add_telegram_channel(self):
        """Test case for handle_add_telegram_channel

        Add telegram channel  # noqa: E501
        """
        pass

    def test_handle_send_notification(self):
        """Test case for handle_send_notification

        Send notification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
