"""
    notifier

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Contact: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.add_telegram_channel_body import AddTelegramChannelBody


class TestAddTelegramChannelBody(unittest.TestCase):
    """AddTelegramChannelBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddTelegramChannelBody(self):
        """Test AddTelegramChannelBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddTelegramChannelBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
