"""
    notifier

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Contact: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.add_channel_body import AddChannelBody


class TestAddChannelBody(unittest.TestCase):
    """AddChannelBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddChannelBody(self):
        """Test AddChannelBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddChannelBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
